### ISSUE TITLE
Integration with SonarQube is not working

### ISSUE THREAD

**Issue by chepe4pi** [travis-ci/docs-travis-ci-com#809]
config

```
addons:
  sonarqube: true
env:
  global:
    - secure: ___SOME_SECURE_CODE____
script:
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN

```
error trace
```
0.26s$ sonar-scanner -Dsonar.login=$SONAR_TOKEN
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/sonarsource/scanner/cli/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
The command "sonar-scanner -Dsonar.login=$SONAR_TOKEN" exited with 1.
Done. Your build exited with 1.
```

**Comment by BanzaiMan** [comment]
Thanks for taking time to open this issue, but this doesn't look like a documentation issue. I'm closing this now.

I think the same issue is https://github.com/travis-ci/travis-ci/issues/6631.
